language: node_js

node_js:
  - 0.12

sudo: required
dist: trusty

install:
  - bundle install
  - npm install -g grunt-cli
  - npm install -g bigcommerce/stencil-cli
  - npm install

script:
  - npm run check
  - grunt check
  - stencil bundle
