language: node_js
node_js:
- 4
sudo: required
dist: trusty
install:
- bundle install
- npm install -g grunt-cli
- npm install -g bigcommerce/stencil-cli
- npm install
script:
- npm run check
- grunt check
- stencil bundle -n Cornerstone
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: MwP32kPFXPBUfm/UGc+gHDlZghETss/APmsufueLtzJPH2aitkh5z+IphC+8gum6OmRm/+GpO7P2xbrgp7A25m5QvwCk7H+xQxISonGqIlkh2F09bYtbGlh/wXZt2wNwl4BpIQC0X7qO/zvmetpVvAmsfMPQAAbhWYp2V+f4uYmqfzQulBVRQnoWpnHJAgQrqFZ6veMk/qFpoU4D+J4XL3bePR6rbYLgVm1hvVRUv0kpPl/jw4XN0oi2mQExGeI2tUWI21L0I4eReZumOKShDc9s8D9+6wyuL03kHi/UY3ZZ7u26hpAcfFWRknV1MpeHbtHg8RL6+KPFcv2SU/RTqBYu1BMpWHUMT8Lffbht0l+qrwKPDfOIhqc6Hbqw8YSXXIGyixqwdKaZ7vJEERxxM+6RYmFjPsPcRgMYXBkEoONHMuXjhJ4kQW0N9q1oq0PWduQ3DCv3vH85aY7bqUZv2DvUV1879s/wnI4FtjErJl9gROcPVj1w1LGgA2LDo2fxEtt5qmmuv0xTgkBH/w6qUmwgda/Pnh7mtZgNMFlEfXEtrUkuv+dJguhygZoO1uFybnkJ8r0K2MakH4LR+cMR4oLII7aHRA9SsLj9Tg2SnXshZTAzQES1P4wyrHQZmATrSoopEPmGSvvO6n9JjPEVz59DHeqlC81syo727OKTjXM=
  file: Cornerstone.zip
  on:
    tags: true
